version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - copyloopvar
    - errorlint
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports
